### ISSUE TITLE
`undefined: unsafe.StringData` on build 1.27-rc.0 with go 1.19

### ISSUE THREAD

**Issue by a7i** [kubernetes/apiserver#92]
I can only compile the latest release candidate with Go 1.20 and unable to compile with 1.19
Isn't it safe to assume that kubernetes libraries support a 3 version skew and therefore support the go version it was compiled with?

```
vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go:286:29: undefined: unsafe.StringData
vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go:297:16: undefined: unsafe.String
vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go:297:30: undefined: unsafe.SliceData
note: module requires Go 1.20

# k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2
vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/cache.go:107:16: undefined: unsafe.String
vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/cache.go:107:30: undefined: unsafe.SliceData
vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope.go:412:29: undefined: unsafe.StringData
note: module requires Go 1.20
make: *** [Makefile:56: build] Error 2
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_descheduler/1100/pull-descheduler-verify-build-master/1639640471053537280

Related PR: https://github.com/kubernetes/kubernetes/pull/115935
Related Commit https://github.com/kubernetes/apiserver/commit/6ab879299def506b51e57960eefb5e937871917f

**Comment by dims** [comment]
this is by design.

we have specified the minimum version of go in the go.mod:
https://github.com/kubernetes/apiserver/blob/master/go.mod#L5

/close
